import MyAddress from "../screens/MyAddress";

const Routes = {
    Authenticated: 'Authenticated',
    NotAuthenticated: "NotAuthenticated",
    MainRoute: "MainRoute",
    HomeTabs: "HomeTabs",
    MainTabs: "MainTabs",
    Splash: "Splash",
    Start: "Start",
    Login: "Login",
    SignUp: "SignUp",
    VerifyCode: "VerifyCode",
    ForgotPassword: "ForgotPassword",
    Search: "Search",
    Home: "Home",
    Categories: "Categories",
    Cart: "Cart",
    CartOutside: "CartOutside",
    Wishlist: "Wishlist",
    WishlistOutside: "WishlistOutside",
    AccountMain: "AccountMain",
    AccountOption: "AccountOption",
    MyAccount: "MyAccount",
    About: "About",
    EditProfile: "EditProfile",
    ChangePswd: "ChangePswd",
    ChangePswdDeepLink: "ChangePswdDeepLink",
    ChangePhoneNumber: "ChangePhoneNumber",
    WebsiteView: 'WebsiteView',
    Settings: 'Settings',
    MyAddress: 'MyAddress',
    AddNewAddress: 'AddNewAddress',
    EditAddress: 'EditAddress',
    VerifyAddress: "VerifyAddress",
    ProductList: "ProductList",
    ProductDetail: "ProductDetail",
    ProductListHome: "ProductListHome",
    BrandListHome: "BrandListHome",
    ProductListSearch: "ProductListSearch",
    WriteReview: "WriteReview",
    AllReviews: "AllReviews",
    Checkout: "Checkout",
    SearchAddressMap: "SearchAddressMap",
    MyOrders: "MyOrders",
    OrderDetail: "OrderDetail",
    TrackOrder: "TrackOrder",
    ProductDetailDeeplink: "ProductDetailDeeplink",
    NotificationSettings: "NotificationSettings",
    MyNotifications: "MyNotifications",
    OrderDetailNotif: "OrderDetailNotif",
    ProductDetailNotif: "ProductDetailNotif",
    ReturnOrder: "ReturnOrder",
    MyOrdersNotif: 'MyOrdersNotif',
    ReturnOrderList: 'ReturnOrderList',
    CartNotif: 'CartNotif',
    Wallet:'Wallet',
    AddWallet:'AddWallet',
    RedemVoucher:'RedemVoucher'
};
export default Routes;
