import LocalizedStrings from 'react-native-localization';

let Strings = new LocalizedStrings({
    en: {
        //navigation titles
        navHome: 'Home',
        navMyAccount: 'My Account',
        navCategories: 'Categories',
        navCart: 'Cart',
        navWishlist: 'Wishlist',
        navAboutApp: 'About Let\'s Buy',
        navProductDetail: 'Product Detail',
        navNewAddress: 'Add New Address',
        navEditAddress: 'Edit Address',
        navMyCart: 'My Cart',
        navCheckout: 'Checkout',
        navShippingInfo: 'Shipping Info',
        navReturnPolicy: 'Return Policy',
        navPrivacyPolicy: 'Privacy Policy',
        navTermsAndConditions: 'Terms and Conditions',
        navAboutUs: 'About Us',
        navMyOrders: 'My Orders',
        navOrderDetails: 'Order Details',
        navWriteReview: 'Write a review',
        navAllReviews: 'All Reviews',
        myAddress: 'My Addresses',
        myWishList: 'My Wishlist',
        settings: 'Settings',
        changePassword: 'Change Password',
        editProfile: 'Edit Profile',
        navTrackOrder: 'Track Order',
        navMyNotifications: 'My Notifications',
        navReturnOrder: 'Return Order',

        //buttons
        signIn: 'Sign In',
        signUp: 'Sign Up',
        skip: 'SKIP',
        continue: 'Continue',
        verify: 'Verify',
        sendCodeAgain: 'SEND CODE AGAIN',
        cancel: 'Cancel',
        saveAddress: 'Save Address',
        updateAndSave: 'Update & Save',
        signOut: 'Sign Out',
        saveUpdate: 'Save & Update',
        ok: 'OK',
        updatePassword: 'Update Password',
        download: 'Download',
        retry: 'Retry',
        resendOTP: 'Resend OTP',
        changePhoneNumber: 'Change Mobile Number',
        viewAll: 'View all',
        sendLink: 'Send Link',
        add: 'Add',
        checkOut: 'CHECKOUT',
        remove: 'Remove',
        delete: 'Delete',
        edit: 'Edit',
        seeMore: 'See more',
        seeLess: 'See less',
        writeReview: 'Write a review',
        viewAllReview: 'View all reviews',
        addToCart: 'Add to cart',
        buyNow: 'Buy Now',
        sortBy: 'Sort by',
        filters: 'Filters',
        helpSupport: 'Help & Support',
        rateApp: 'Rate App',
        shareApp: 'Share App',
        moveToWishList: 'Move to Wishlist',
        changeLanguage: 'Change Language',
        submit: 'SUBMIT',
        addImages: 'Add images',
        openGallery: 'Open Gallery',
        openCamera: 'Open Camera',
        pickImage: 'Pick an Image',
        apply: 'Apply',
        clear: 'Clear',
        filterBy: 'Filter By',
        verified: 'Verified',
        yes: 'Yes',
        no: 'No',
        addItems: 'Add Items',
        addLocation: 'Add Location',
        applied: 'Applied',
        applyString: 'Apply',
        searchOnMap: 'Select location on map',
        confirmOrder: "Confirm Order",
        trackOrder: 'Track Order',
        cancelOrder: 'Cancel Order',
        returnOrder: 'Return Order',
        remindLater: 'Remind Me Later',
        callUs: 'Call Us',
        whatsapp: 'WhatsApp',
        feedbackEmail: 'Email',
        liveChat: 'Live Chat',
        englishLabel: 'English',
        arabicLabel: 'Arabic',
        removeAll: 'Remove all',
        selectAll: 'Select all',


        //input labels
        email: 'Email',
        firstName: 'First Name',
        lastName: 'Last Name',
        fullName: 'Full Name',
        password: 'Password',
        mobileNumber: 'Mobile Number',
        oldPassword: 'Old Password',
        newPassword: 'New Password',
        confirmNewPassword: 'Confirm New Password',
        addressLabel: 'Address label',
        neighbourHood: 'City',
        streetName: 'Neighborhood/Street Name',
        city: 'City',
        zipCode: 'Post/Zip Code',
        state: 'State/Province',
        country: 'Country/Region',
        reviewFullName: 'Full Name',
        mobile: 'Mobile',
        yourName: 'Your Name',
        cod: 'Cash on Delivery',
        bank_transfer:'Bank Transfer',
        "tap-card":'Credit or Debit Card',
        "tap-mada":'MADA Payment',


        //placeholders
        mobileNumberPlaceholder: '5XXXXXXX',
        addressPlaceholder: 'eg.Home, Work',
        searchPlaceholder: 'Search brands, products',
        writeYourReview: 'Write your review here...',
        couponCodePlaceholder: 'Enter Coupon Code',
        giftCodePlaceholder: 'Enter Gift Code',
        reasonPlaceholder: 'Write your reason here...',
        returnReasonPlaceholder: "Faulty or other details...",


        //messages
        maintenanceMessage: '\n\nCurrently, we are under server maintenance. Please come back after some time. \n\nSorry for the Inconvenience and we appreciate your patience.\n\n',
        thankYouRegister: 'Thank you for registering in Let\'s Buy. We\'ll send you verification code on your mobile number.',
        errorMessage: "Something went wrong. Please try again later",
        updateMessage: 'New app version available for update.',
        internalServerError: "Internal Server error.Please try again later",
        noAttemptsError: 'You have 0 attempt left, Please try again after 1 hour.',
        codeNote: 'Your code will expire in 10 minutes',
        mobileNumberNote: 'Your code has been sent to ',
        settingsNote: 'Set your preferences',
        retryAfterThirty: 'Resend OTP after 60 seconds',
        passwordUpdateSuccess: 'Password updated successfully.',
        forgotSuccessMessage: 'A password reset link has been sent to your register mobile number',
        deleteItemToCartMessage: 'You want to delete item from cart',
        deleteItemToCartAndMoveToWishlist: 'You want to remove item from cart and move to wishlist',
        productUpdateCartMessage: 'Product updated in cart',
        productMoveToWishlist: 'Product moved to wishlist',
        requestLinkMessage: 'You will have to request reset link again.',
        resetSuccessPassword: 'Password successfully reset',
        loginNewPassword: 'Please login using your new password.',
        otpSendMessage: 'OTP has been sent to the new number',
        productAddWishlist: 'Product added to wishlist',
        productRemoveWishlist: 'Product removed from wishlist',
        productAddCart: 'Product added to cart',
        locationDisabledMessage: "Location permission is required to fetch address",
        enterRemainingDetails: 'Please enter remaining details and register',
        errOrderDetail: "Could not fetch details",
        errCouldNotGetProductDetail: "Could not fetch product detail",
        noProductsFound: "No products found",
        couldNotAuthenticate: "Could not authenticate reset link",
        noOrders: "No orders found",
        appRestart: 'The app will restart now.',
        cancelVerifyMessage: "You will be logged out.\nYour cart and wishlist have been saved. Please verify your account to retrieve this information",
        cardPaymentError: 'This payment method is currently unavailable',
        bankTransferInfo: 'Please see bank transfer information below',
        noNotifications: 'No notifications received',
        trackingDetailLoadingMessage: 'We are fetching data from our tracking partners',
        placeOrderConfirmMessage: 'Do you want to place this order?',
        troubleMessage: 'Hello,\nI need your assistance. \nHere are my details:\n',
        troubleSubject: 'Support request',
        supportEmailError: 'Could not send email',
        callingNotSupport: 'Your device not support calling.',
        additionalItemsWarning: 'You have additional items in cart.\nThey will be checked-out along with current product. Continue?',
        noAddressAddedError: 'You don\'t have any verified address. Add an address or verify your added address',

        //Validation
        phoneBlank: 'Please enter mobile number',
        phoneLength: 'Mobile number must between 7 to 12 digits',
        phoneInvalid: 'Mobile number must only contain numeric values',
        phoneWithoutZero: "Please enter the phone number without '0'",
        passwordBlank: 'Enter password',
        passwordInvalid: 'Password must not contain whitespaces',
        passwordLength: 'Password must be 6 character long',
        emailInvalid: 'Enter valid email address',
        emailBlank: 'Enter email address',
        otpCodeInvalid: 'OTP code must be number.',
        emptyCode: 'Please enter code',
        reviewBlankError: 'Please enter review text',
        nameBlank: "Please enter Name",
        nameLength: "Name characters exceed limit",
        voucherBlank: "Please enter Voucher",
        voucherLength: "Voucher characters exceed limit",
        nameInvalid: 'Name is invalid',
        ratingCountError: "Please add rating",
        optionsError: 'Please select all options',
        countryInvalid: 'Selected country invalid',
        stateInvalid: 'Selected state invalid',
        reasonTextBlank: 'Please enter reason',
        itemsSelectError: 'Please select items for return',
        returnReasonError: 'Please select reason for return',
        productOpenedError: 'Please select answer',
        streetNameBlank: 'Please add street name',
        neighbourHoodInvalid: 'Neighbourhood characters exceed limit',
        addressLabelInvalid: 'Label characters exceed limit',
        zipCodeBlank: 'Please enter ZipCode',
        zipCodeInvalid: 'Zip Code is invalid',
        zipCodeLong: 'Zip Code must be 5 to 6 digits',
        countryBlank: 'Please select country',
        stateBlank: 'Please select state',

        //captions
        forgotPassword: 'Forgot password?',
        signInWith: 'or sign in with',
        noHaveAccount: 'Don\'t have and account? ',
        haveAccount: 'Have an account? ',
        signUpNoteOne: 'By signing up you accept all our ',
        signUpNoteTwo: ' & ',
        termCondition: 'Terms',
        policies: 'Policies',
        verifyCode: 'Verify Code',
        codeLabel: 'Verification Code',
        error: 'Error',
        success: 'Success',
        information: 'Information',
        updateAvailable: 'Update available',
        appName: 'Let\'s Buy',
        linkUnableToOpen: 'Unable to open link',
        youHave: 'You have',
        attemptsLeft: 'attempt left',
        tagLine: 'T   o      B   e      S   t   y   l   i   s   h',
        welcome: 'Welcome',
        hello: 'Hello',
        pleaseWait: 'Please wait...',
        loadingReviews: 'Loading more reviews ...',
        pullRefresh: 'Pull To Refresh',
        areUSure: 'Are you sure?',
        item: 'Item',
        items: 'Items',
        noItems: 'No items',
        freeShipping: 'Free Shipping',
        noProductsInCard: 'Your cart is empty!',
        quantity: 'Quantity',
        quantityPrice: 'Quantity Price',
        cartTotal: 'Cart Total',
        updateYourPassword: 'Update your password',
        enterNewMobileForOTP: 'Enter new mobile number to receive OTP',
        updateDetails: 'Update your details',
        forgotPasswordTitle: 'Forgot Password',
        getCodeMessage: 'Enter your registered email to get the code',
        welcomeBack: 'Welcome Back',
        signInContinue: 'Sign in to continue',
        deleteAddress: 'you want to delete address?',
        verifyMobile: 'Verify Mobile No.',
        noAddress: 'No Address have been added',
        features: 'Features',
        descriptions: 'Descriptions',
        similarProdcuts: 'Similar Products',
        recentlyViewed: 'Recently Viewed',
        outOfStock: 'Out of Stock',
        loadingMoreProducts: 'Loading more products ...',
        emptyWishlist: 'No items in your wishlist!',
        createAccount: 'Create Your Account',
        justAStep: 'Just a step to go.',
        yourReview: 'Your Review',
        reviews: 'Reviews',
        toGet: 'to get',
        youAreEligible: 'You are eligible for',
        goShopping: 'Go Shopping',
        only: 'Only',
        left: 'left',
        chooseColor: 'choose color',
        chooseSize: 'choose size',
        chooseDeliveryAddress: 'Choose delivery address',
        paymentMethodTitle: 'Payment Methods',
        off: 'Off',
        all: 'all',
        dragMap: "Drag map to address",
        fetchAgain: "Fetch again",
        waitingForLocation: "Waiting for location",
        addressLoading: "Loading...",
        locationDisabled: "Location permission disabled",
        couponCode: "Coupon Code",
        giftCode: "Gift Code",
        choose: 'choose',
        total: 'Total',
        shippingQuery: 'shipping',
        followUsOn: 'Follow us on',
        categoryAll: 'All',
        shippingMethodTitle: "Shipping Methods",
        orderSummery: "Order Summary",
        orderID: 'Order ID',
        returnID: 'Return ID',
        dateAddedLabel: 'Order Placed',
        dateStatusLabel: 'Order',
        orderShippingTitle: 'Shipping Method',
        orderShippingAddress: 'Shipping Address',
        loadingOrders: 'Loading more orders...',
        inStock: 'In Stock',
        warning: 'Warning',
        rateProduct: 'Rate the product',
        selectLanguage: 'Select Language',
        customerSupportTitle: 'Customer Service',
        allOrders: 'All Orders',
        cancellationReason: 'Cancellation Reason',
        otherReason: 'Other',
        orderContactInfo: 'Contact Info',
        orderPaymentMethod: 'Payment Method',
        order: 'Order',
        productOptions: 'Product Options',
        emailNotifLabel: 'Email notifications',
        smsNotifLabel: 'SMS notifications',
        pushNotifLabel: 'Push notifications',
        notificationTitle: 'Notifications',
        notificationSettingCaption: 'Enable or disable notifications',
        select: 'select',
        loadingNotifications: 'Loading more notifications...',
        productIsOpened: "Product is opened",
        selectItemsReturn: "Select items to return",
        returnReasonTitle: 'Reason for returning order',
        returnComments: 'Comments',
        returnedStatus: 'Returned',
        makeDefault: 'Make Default',
        applePay:'Apple Pay'
    }
});

export default Strings;
